lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack
    resources "/messages", MessageController
    resources "/users", UserController
    get "/", PageController, :index
    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout
  end
  # Other scopes may use custom stacks.
   scope "/api", MicroblogWeb do
     pipe_through :api
     resources "/likes", LikeController, except: [:new, :edit]
   end
end

lib/microblog_web/views/layout_view.ex
defmodule MicroblogWeb.LayoutView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Microblog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>
  <body>
   <nav class="navbar navbar-dark bg-dark navbar-expand-md">
      <a class="navbar-brand" href="/">Microblog</a>

      <%= if @current_user do %>
        <span class="text-light">
          <%= @current_user.email %> |
          <%= link("logout", to: session_path(@conn, :logout), method: :delete) %>
        </span>
      <% else %>
        <%= form_for @conn, session_path(@conn, :login),
              [as: "user", class: "form-inline w-75"], fn f -> %>
          <input type="text" placeholder="username" class="form-control" name="username">
          <input type="password" placeholder="password" class="form-control" name="password">
          <input type="submit" value="Log in" class="btn btn-primary">
        <% end %>
        <span class="btn btn-secondary"><%= link "New User", to: user_path(@conn, :new) %></span>
      <% end %>
   </nav>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 my-2">
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <% end %>
        </div>
      </div>
      <main role="main">
       <%= render @view_module, @view_template, assigns %>
     </main>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>